### PR TITLE
Initial s390x relocation support

### PR DESCRIPTION
**Pull request by stefan-sf-ibm**
This adds initial s390x relocation support as defined by the [ABI](https://github.com/IBM/s390x-abi/releases/download/v1.6/lzsabi_s390x.pdf).

### CODE REVIEW

**Comment by sevaa** [comment]
Any chance we could get a test binary to go along with that?

**Comment by stefan-sf-ibm** [comment]
Sure, I've followed the existing examples in `test/testfiles_for_readelf` and added a binary `s390x-relocs.o.elf`.

**Comment by sevaa** [comment]
Thanks. Did you get a chance to run it? To test the new binary alone, run the following from the project root (assuming Linux):

```python3 test/run_readelf_tests.py test/testfiles_for_readelf/s390x-relocs.o.elf```

On Windows, it's possible too, but more involved than that. On Mac, I've never tried.

**Review by eliben — COMMENTED** [review]
The PR looks good to me, but PTAL at the test failures

**Comment by stefan-sf-ibm** [comment]
@sevaa thanks for pointing this out. I only ran my own local tests. Running the testsuite I found a typo where s390x was lower and upper case in `ENUM_RELOC_TYPE_S390X`. I stream lined it in upper case style. Beside that a `_DESCR_E_MACHINE` entry was missing.

I also changed the existing entry of `get_machine_arch` from returning `IBM System/390` to `IBM S/390` in order to follow [readelf.c](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=binutils/readelf.c;h=701ca73a7c229720b6f6485e392004d03806dd99;hb=HEAD#l2865).

Testsuite runs fine for me, now:
```
$ python3 test/run_readelf_tests.py test/testfiles_for_readelf/s390x-relocs.o.elf 
Test file 'test/testfiles_for_readelf/s390x-relocs.o.elf'

Conclusion: SUCCESS
```

**Review by eliben — APPROVED** [review]

**Pull request merged**
