### PR TITLE
Added Dwarfv5 CU headers

### PR DESCRIPTION
**Pull request by WillDenissen**
Added support for parsing DWARFv5 7.5.1.{1,2,3} CU headers, and dumping in readelf.py

Aligned readelf.py output with reference readelf
Added test file compiled with -gdebug_types-section to readelf tests

Partially addresses Issues: 
- issue: #325 #311 

Note it does not address issue #193

### CODE REVIEW

**Comment by eliben** [comment]
@sevaa please help review

**Comment by sevaa** [comment]
Okay, the problem is real - the CU header format in v5 varies with unit type, which is one of the leading fields. There are two possible flavors there. 

The proposed patch slightly breaks the API - the field header.unit_type used to be numeric, the patch makes it a string from the `DW_UT_` enum.

Caching/reuse of lineprograms is a good idea regardless.

**Comment by eliben** [comment]
> Okay, the problem is real - the CU header format in v5 varies with unit type, which is one of the leading fields. There are two possible flavors there.
> 
> The proposed patch slightly breaks the API - the field header.unit_type in `CompileUnit` used to be numeric, the patch makes it a string from the `DW_UT_` enum.
> 
> Caching/reuse of lineprograms is a good idea regardless.

This sounds good. Does the PR LGTY?

**Comment by sevaa** [comment]
Do we take an issue with the change of that one header field's format that I've mentioned?

**Comment by eliben** [comment]
> Do we take an issue with the change of that one header field's format that I've mentioned?

I think it's fine, seems like a reasonable change to clarify an untyped int to an actual enum. As mentioned before, I'm not hugely worried about API changes at this level of specificity.

**Comment by sevaa** [comment]
Okay, then no objections.

**Review by eliben — APPROVED** [review]
Nice work!
Thanks for the contribution

**Pull request merged**
