### PR TITLE
Fix #103

### LINKED ISSUE #103: Bug in interpreter of DW_CFA_remember_state
Dear all

I believe there is a small bug in the interpreter of DW_CFA_remember_state.  The interpreter pushes the current line on a stack, but, due to sharing, subsequent bytecode instructions can modify the pushed line whenever they modify the current line.

For instance, this FDE entry:

00000088 000000000000001c 0000005c FDE cie=00000030 pc= 0000000000400980.. 00000000004009d1
  DW_CFA_advance_loc: 4 to 0000000000400984
  DW_CFA_def_cfa_offset: 24
  DW_CFA_advance_loc1: 64 to 00000000004009c4
  DW_CFA_remember_state
  DW_CFA_def_cfa_offset: 8
  DW_CFA_advance_loc: 4 to 00000000004009c8
  DW_CFA_restore_state

should generate:

00000060 000000000000001c 00000034 FDE cie=00000030 pc=0000000000400980..00000000004009d1
   LOC           CFA      ra
0000000000400980 rsp+8    c-8
0000000000400984 rsp+24   c-8
00000000004009c4 rsp+8    c-8
00000000004009c8 rsp+24   c-8

 (observe the last +24, due to remembering the line for 400984), while it results in:

00000060 000000000000001c 0000000000000034 FDE cie=00000030 pc=0000000000400980..00000000004009d1
   LOC   CFA      ra
0000000000400980 rsp+8    c-8
0000000000400984 rsp+24   c-8
00000000004009c4 rsp+8    c-8
00000000004009c8 rsp+8    c-8

The final +8 is due due the update to the current line in 4009c4.  

I believe that deep-copying the current line before pushing it on the stack + updating the pc when pulling is a simple fix (patch below).

I cannot submit you a binary to reproduce easily as the FDE entry was obtained by parsing eh_frame info via an eh_frame parser I implemented (that I will eventually contribute to pyelftools) and not by parsing debug_frames.

-francesco

```
Index: pyelftools/elftools/dwarf/callframe.py
===================================================================
--- pyelftools/elftools/dwarf/callframe.py  (original)
+++ pyelftools/elftools/dwarf/callframe.py  (working copy)
@@ -501,9 +501,11 @@
                 else:
                     cur_line.pop(instr.args[0], None)
             elif name == 'DW_CFA_remember_state':
-                line_stack.append(cur_line)
+                line_stack.append(copy.deepcopy(cur_line))
             elif name == 'DW_CFA_restore_state':
+                pc = cur_line['pc'] 
                 cur_line = line_stack.pop()
+                cur_line['pc'] = pc

         # The current line is appended to the table after all instructions
         # have ended, in any case (even if there were no instructions).
```

### PR DESCRIPTION
**Pull request by ulysses4ever**

### CODE REVIEW

**Comment by eliben** [comment]
Thanks for the contribution. Since this code is subtle I'd like to have a test. I asked in #103 about supplying a full test case, but in the mean-time a unit test could be created, similar to `test/test_callframe.py` that creates a simple program and tests that this works correctly. Could you add a test for the PR?

**Comment by ulysses4ever** [comment]
Hi, @eliben! The need for the test cases sounds perfectly reasonable to me, but there is a problem here: I have no idea about this project whatsoever. I just created this PR because @francesco-zappa-nardelli asked me to. I could add anything he or you want to this PR but I cannot create this myself, unfortunately.

**Comment by eliben** [comment]
I've also left a comment for Francesco on the original issue, since I think the original test cases could be used now. 

Otherwise I'll have to put this PR on hold until a test is provided - I'm not feeling comfortable adding this code without direct testing, since this is one of the subtlest parts of the project

**Comment by ulysses4ever** [comment]
Sounds good for me. Lets wait for Francesco's respond.

**Comment by francesco-zappa-nardelli** [comment]
Hi all.  It took me a while to regenerate a binary that exhibits this problem, but here you go.  The relevant x86_64 binary is available from: [https://www.di.ens.fr/~zappa/stuff/reduced](https://www.di.ens.fr/~zappa/stuff/reduced) .   readelf -wF correctly outputs:

```00000088 000000000000001c 0000005c FDE cie=00000030 pc=000000000040048d..0000000000400515
   LOC           CFA      rbx   ra      
000000000040048d rsp+8    u     c-8   
000000000040048e rsp+16   c-16  c-8   
0000000000400507 rsp+8    c-16  c-8   
0000000000400508 rsp+16   c-16  c-8 
```

while pyelftools/readelf misexecutes the remember_state / restore_state instructions of the eh_frame table

```00000088 000000000000001c 0000005c FDE cie=00000030 pc=000000000040048d..0000000000400515
  DW_CFA_advance_loc: 1 to 000000000040048e
  DW_CFA_def_cfa_offset: 16
  DW_CFA_offset: r3 (rbx) at cfa-16
  DW_CFA_advance_loc1: 121 to 0000000000400507
  DW_CFA_remember_state
  DW_CFA_def_cfa_offset: 8
  DW_CFA_advance_loc: 1 to 0000000000400508
  DW_CFA_restore_state
  DW_CFA_nop
  DW_CFA_nop
  DW_CFA_nop
```

generating:

```00000088 000000000000001c 0000005c FDE cie=00000030 pc=000000000040048d..0000000000400515
   LOC           CFA      rbx   ra
000000000040048d rsp+8    u     c-8   
000000000040048e rsp+16   c-16  c-8   
0000000000400507 rsp+8    c-16  c-8   
0000000000400508 rsp+8    c-16  c-8   
```
(observe the rsp+8 instead of rsp+16 in the last line).

**Comment by eliben** [comment]
Closing, given that #184 was committed.

**Pull request closed without merging**
