### PR TITLE
Add PS3/CellOS OSABI identifier

### PR DESCRIPTION
**Pull request by iMoD1998**
Hello, this adds the OSABI ELFOSABI_CELLOS_LV2 for PS3.

### CODE REVIEW

**Review by eliben — COMMENTED** [review]
I cannot find references to this enum value anywhere online - can you point to some reference documentation that describes it?

**Comment by iMoD1998** [comment]
> I cannot find references to this enum value anywhere online - can you point to some reference documentation that describes it?

My apologies, its very undocumented but here is something.

https://www.psdevwiki.com/ps3/SELF_-_SPRX#OS_ABI_identification

I have binaries I can provide that also use this value if needed.

**Comment by eliben** [comment]
Thanks. Any particular reason you chose a slightly different constant name - with `OS` in it; without it, the value is definitely more googleable :)

**Comment by iMoD1998** [comment]
I was using a readelf from an SDK and thats what it output as the OSABI.

**Comment by iMoD1998** [comment]
image

**Comment by eliben** [comment]
If that's the reason, I suggest leaving the `OS` out of the constant name. You already have the readelf-matching name set in descriptions.py

**Comment by iMoD1998** [comment]
I agree, just changed it.

**Comment by iMoD1998** [comment]
Whoops missed a comma.

**Review by eliben — APPROVED** [review]

**Pull request merged**
