### PR TITLE
Added SHT_GNU_ATTRIBUTES to ENUM_SH_TYPE

### PR DESCRIPTION
**Pull request by michalmalik**

### CODE REVIEW

**Comment by eliben** [comment]
Thanks. According the Travis this PR breaks the tests though - can you take a look?

**Comment by michalmalik** [comment]
```
Running '/usr/bin/python test/run_all_unittests.py'
...................................
----------------------------------------------------------------------
Ran 35 tests in 0.303s

OK
Running '/usr/bin/python test/run_examples_test.py'
Example './examples/dwarf_location_lists.py'
Example './examples/elf_show_debug_sections.py'
Example './examples/dwarf_die_tree.py'
Example './examples/elf_relocations.py'
Example './examples/elf_low_high_api.py'
Example './examples/dwarf_decode_address.py'
Example './examples/dwarf_range_lists.py'
Example './examples/elfclass_address_size.py'
Example './examples/examine_dwarf_info.py'

Conclusion: SUCCESS
Running '/usr/bin/python test/run_readelf_tests.py'
Test file 'test/testfiles_for_readelf/penalty_64_clang.o.elf'
Test file 'test/testfiles_for_readelf/simple_aarch64_gcc.o.elf'
Test file 'test/testfiles_for_readelf/simple_arm_gcc.o.elf'
Test file 'test/testfiles_for_readelf/penalty_64_gcc.o.elf'
Test file 'test/testfiles_for_readelf/update32.o.elf'
Test file 'test/testfiles_for_readelf/exe_stripped64.elf'
Test file 'test/testfiles_for_readelf/libelf0_8_13_32bit.so.elf'
Test file 'test/testfiles_for_readelf/obj_simple32.o.elf'
Test file 'test/testfiles_for_readelf/exe_simple32.elf'
Test file 'test/testfiles_for_readelf/simple_mips_gcc.o.elf'
.......................FAIL
....for option "-e"
....Output #1 is readelf, Output #2 is pyelftools
@@ Mismatch on line #43:
>>  [21] .gnu.attributes   loos+ffffff5    00000000 0003db 000010 00      0   0  1<<
>>  [21] .gnu.attributes   <unknown>       00000000 0003db 000010 00      0   0  1<<
 ([('equal', 0, 25, 0, 25), ('replace', 25, 26, 25, 30), ('equal', 26, 27, 30, 31), ('replace', 27, 37, 31, 37), ('equal', 37, 80, 37, 80)])
@@ Output #1 dumped to file: /tmp/out1_iTXvMb.stdout
@@ Output #2 dumped to file: /tmp/out2_s3ym27.stdout

Conclusion: FAIL
```

I found a bug here: https://github.com/eliben/pyelftools/blob/master/elftools/elf/descriptions.py#L58

```python
def describe_sh_type(x):
    if x in _DESCR_SH_TYPE:
        return _DESCR_SH_TYPE.get(x)
    elif x >= ENUM_SH_TYPE['SHT_LOOS'] and x < ENUM_SH_TYPE['SHT_GNU_versym']:
        return 'loos+%lx' % (x - ENUM_SH_TYPE['SHT_LOOS'])
    else:
        return _unknown
```

I commited a change to elftools/elf/descriptions.py to fix this.

**Comment by michalmalik** [comment]
Looks like the bug is also present in the ```describe_p_type(x)``` function.

**Comment by eliben** [comment]
@michalmalik I looked into it - as I've said in the commit comment, I'm not sure why this is a bug. Is there a reason to not just add the new enum to the descriptions table?

**Comment by michalmalik** [comment]
If I understand it correctly, in one of your tests, you are comparing the output of the real readelf utility and the output of your utility, which you made using pyelftools. Are you suggesting I add the SHT_ to the descriptions table like this?

```python
SHT_GNU_ATTRIBUTES="loos+ffffff5"
```
I don't find it particularly descriptive and I think it's a better way of handling enums that even the readelf utility does not describe properly, since it's SHT_LOOS + <something>.

**Comment by eliben** [comment]
Ah, I see. Sorry, I didn't notice this attribute is in the `LOOS+` range. Just a couple small requests and this is good to go:

1. Please add a comment in `describe_sh_type` explaining the new logic
2. Squash the two commits in this PR into one

**Comment by eliben** [comment]
Ping - any progress?

**Comment by eliben** [comment]
Closing due to inactivity. If anyone is willing to reopen and rebase this, please open a new PR

**Pull request closed without merging**
