### PR TITLE
dwarf .debug_types and .debug_macros

### PR DESCRIPTION
**Pull request by mdmillerii**
Here is a series that adds .debug_types with an api similar to random-die, and also a .debug_macros with an API based on location lists.

Both have readelf based testing, including a new assembly generated dwarf for some macinfo corners.

### CODE REVIEW

**Comment by mdmillerii** [comment]
I considered the changes in dwarf v5, notibly that the macinfo will be replace with macros that have section contribution headers, and that type units will be 1 of 6 possible types in the debug_info section.

Addresses #193 and #199.

**Comment by mdmillerii** [comment]
Fixed some tabs that crept in a refactor indent.

Merging with #264 will hit both sides: DIE can lookup by sig and sig type DIE can lookup exact DIE.
I'll work on testing a merge branch.

**Comment by eliben** [comment]
It's not clear to me how this relates to #264 -- could you please provide more information?

**Comment by mdmillerii** [comment]
These are complementary to #264, just that the merge will use features from both sides to fully integrate.  I did a test merge and can rebase this after the other.

**Comment by Lordy2001** [comment]
Does this branch support both V4 .debug_macinfo as well as V5 .debug_macro sections?  It looks like the code in the readelf.py only pulls in .debug_macinfo.

**Comment by mdmillerii** [comment]
This code only supports V4.  I have read V5 but not implmented the additional parsing.
Also, without --strict-dwarf gcc aparently produces GNU_macros sections which is probably closer to a (subset of?) V5 with its own dies.

I still need to rebase on 264.

**Comment by mdmillerii** [comment]
This is now rebased on number 264.

**Comment by eliben** [comment]
@mdmillerii could you please fix the conflicts?

**Comment by eliben** [comment]
Closing this PR for now. Please reopen if there's renewed interest in working on this.

**Pull request closed without merging**
