### PR TITLE
get_string of StringTableSection return ascii-decoded strings now

### PR DESCRIPTION
**Pull request by JaySon-Huang**
simply decode the bytes as ascii strings.

### CODE REVIEW

**Comment by eliben** [comment]
Thanks. I hope to have time to review this in the next few days.

Also note that you have the build failing on 3.x

**Comment by JaySon-Huang** [comment]
Oh.. I run the `run_readelf_tests.py` under my virtual machine.
and I forgot use Python3 to run that test.

I will fix it.

**Comment by eliben** [comment]
The change looks reasonable to me. Please squash into a single commit. I'll give it another look and then will merge.

**Comment by JaySon-Huang** [comment]
I'm not clearly with "squash into a single commit", dose it means the  "Hard mode: Squash commits" in this page http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit ?

**Comment by eliben** [comment]
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by eliben** [comment]
Merged in #75

**Pull request closed without merging**
