### PR TITLE
callframe.py: fix DW_EH_PE_absptr decoding

### PR DESCRIPTION
**Pull request by pmderodat**
Hello,

The second commit fixes the bug uncovered by #288 and includes the reproducer as a new testcase, and the first commit extends relocations parsing to handle the special ELF64 MIPS format… so that the second commit’s test works properly.

Thanks,

### CODE REVIEW

**Comment by eliben** [comment]
Thanks for the fix! @rhelmot would you mind reviewing, since you opened #288?

**Comment by rhelmot** [comment]
Incredible, the mips64 fixes actually let me remove some hacks from angr that were hacking around the relocation stuff. I can verify that everything loads correctly with this patch.

**Comment by rhelmot** [comment]
Also, to provide attribution: the test file comes from apt-cacher-ng_2-2_mips64el in debian

**Comment by pmderodat** [comment]
Glad to hear that, thank you for letting us know. :-) Do you think we should rename the test file?

**Comment by rhelmot** [comment]
Probably? I don't really care about the name but there might be licensing requirements to distribute it

**Comment by eliben** [comment]
Is there a chance to reproduce the issue in some clean-slate mips64 binary? E.g. concoct a simple C file that - when compiled - would manifest it?

**Pull request merged**
