### PR TITLE
[RISCV] Add GNU note property and CFI support

### PR DESCRIPTION
**Pull request by jerryzj**
- Based on https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/417

### CODE REVIEW

**Comment by sevaa** [comment]
Looks like the RISCV people took a page from the ARM people. :) No objections - once the autotest passes.

**Comment by jerryzj** [comment]
> Looks like the RISCV people took a page from the ARM people. :) No objections - once the autotest passes.
> 
> EDIT: now that I look at that - no new binaries. I take it, one of the existing binaries in the corpus had RISCV notes, and **GNU readelf doesn't dump them properly**, and neither did pyelftools, but now pyelftools does and there is a discrepancy in readelf output? If that's the case, deal with it how we normally deal with readelf deficiencies: file a bug against binutils ([sourceware.org/bugzilla](https://sourceware.org/bugzilla/)), and exclude the offending file from the relevant readelf test (with a comment mentioning bug no). Like it was done in #563.

@sevaa yeap, since CFI is still a new feature for RISC-V, the binutils support is not upstreamed by us. But my local testing shows the newly added binary test can PASS

* readelf

```
riscv64-unknown-linux-gnu-readelf -n  ./test/testfiles_for_readelf/riscv-cfi-zicfilp-zicfiss.elf

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0
      Properties: RISC-V AND feature: ZICFILP, ZICFISS
```

* pyelftools

```
python3 ./scripts/readelf.py -n  ./test/testfiles_for_readelf/riscv-cfi-zicfilp-zicfiss.elf

Displaying notes found in: .note.gnu.property
  Owner                Data size        Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0 (program properties)
      Properties: RISC-V AND feature: ZICFILP, ZICFISS
```

Maybe we should keep this as a draft until the binutils are supported.

**Comment by sevaa** [comment]
If we keep this as a draft until the next release of binutils, the main branch of pyelftools will get more commits and this PR would need a rebase and maybe a manual merge. If you ask me, we should exclude the binary/test combination with a comment, merge now, and remove the test exclusion when GNU readelf catches up. @eliben what do you think?

**Comment by eliben** [comment]
@sevaa yep that sounds reasonable to me

**Comment by jerryzj** [comment]
@sevaa @eliben okay, I've dropped the test and will have another PR for it.

**Review by eliben — APPROVED** [review]

**Pull request merged**
