### PR TITLE
fix wrong prpsinfo in 32bit coredump

### PR DESCRIPTION
**Pull request by Kyle-Kyle**
According to https://elixir.bootlin.com/linux/v5.10.7/source/include/linux/elfcore.h
ELF PRPSINFO is defined as 
~~~
struct elf_prpsinfo
{
	char	pr_state;	/* numeric process state */
	char	pr_sname;	/* char for pr_state */
	char	pr_zomb;	/* zombie */
	char	pr_nice;	/* nice val */
	unsigned long pr_flag;	/* flags */
	__kernel_uid_t	pr_uid;
	__kernel_gid_t	pr_gid;
	pid_t	pr_pid, pr_ppid, pr_pgrp, pr_sid;
	/* Lots missing */
	char	pr_fname[16];	/* filename of executable */
	char	pr_psargs[ELF_PRARGSZ];	/* initial part of arg list */
};
~~~
and `pid_t` is defined at
~~~
typedef __kernel_pid_t		pid_t;
~~~
`__kernel_pid_t` is defined at 
~~~
typedef int		__kernel_pid_t;
~~~

so `pr_pid, pr_ppid, pr_pgrp, pr_sid` should be all 4bytes

### CODE REVIEW

**Comment by eliben** [comment]
@zlobober -- thoughts? [I believe you've added this code in #147]

**Comment by zlobober** [comment]
Sorry for the delay, as usual I've accidentally read notification from my mobile phone and forgot to mark it unread :)

Seems OK to me. What do you think about generating test core dump file and adding a test similar to the existing one here: https://github.com/eliben/pyelftools/blob/master/test/test_core_notes.py#L21? AFAIR, I've just written a simple C program invoking abort() and canonized the expected values.

**Comment by Kyle-Kyle** [comment]
@zlobober done

**Comment by Kyle-Kyle** [comment]
ping

**Review by zlobober — APPROVED** [review]
LGTM

**Review by eliben — APPROVED** [review]
Thanks for the PR, and thanks @zlobober for the review!

**Pull request merged**
