### PR TITLE
Add DW_TAG_GNU_call_site* for better dumping.

### PR DESCRIPTION
**Pull request by sethml**
This comes up for functions which have tail-calls optimized.

### CODE REVIEW

**Comment by eliben** [comment]
Is there any chance you have a test file that can tickle this, and can be placed in the readelf-comparison test suite?

**Comment by sethml** [comment]
Added a test file, and improved formatting to match readelf a bit better.

**Comment by eliben** [comment]
Thanks! Just one more thing - please squash PR into a single commit and then it's ready to go

**Comment by sethml** [comment]
Squashed.

**Pull request merged**
