### PR TITLE
Add support for bytes-like object as input stream

### PR DESCRIPTION
**Pull request by dungsaga**
when input is of type bytes or bytearray, convert it to a binary stream

### CODE REVIEW

**Review by eliben — COMMENTED** [review]
It's not clear to me why this is needed in pyelftools -- can you clarify?

Can't the caller wrap whatever they need in `BytesIO` if needed?

**Comment by eliben** [comment]
If you can find additional evidence that this feature was requested in the past, I'll consider it

**Comment by dungsaga** [comment]
I think it's easier to wrap it inside pyelftools than repeatedly wrap it every time I need to use pyelftools. I work with byte buffers more often than working with files.

**Comment by dungsaga** [comment]
@eliben do you think that my reason is enough for this PR?

**Comment by eliben** [comment]
Sorry, I don't think it adds sufficient value and I haven't seen any additional support in the ~month this issue has been open.

In the fullness of time it's possible to bloat any library with additions like these that make things a tiny bit more convenient, but at the end of the day there are harmful effects like increased complexity, additional axes on the testing matrix, and so on.

**Pull request closed without merging**
